Name: pbsclusterviz
Version: 0.7a
Release: 4%{?dist}
Summary: PBS Cluster Visualization

Group: Applications/Engineering
License: GPLv2+
Url: https://github.com/paultcochrane/pbsclusterviz
Source0: https://github.com/paultcochrane/%{name}/releases/download/v%{version}/%{name}-%{version}.tar.gz

# for some reason GitHub downloads files via web browser with the repository
# name prepended to the tarball name, however via wget or curl the
# repository name isn't prepended.  Also, when the tarball is downloaded
# via wget/curl, the ".tar.gz" gets removed from the file name.  This
# doesn't happen via a web browser.  This is *very* strange.
# I've tried to correct this behaviour by uploading a tarball of the sources
# as generated by "python setup.py bdist".  This downloads the correct file
# via both web browser and wget/curl, however spectool is unable to save
# to the correct filename.

BuildRequires: python2-devel, vtk-python, libxml2-python, desktop-file-utils
Requires: python, vtk-python, libxml2-python
BuildArch: noarch

%description
PBS Cluster Viz is a project to display information useful to admins and
users about a computing cluster managed by a PBS-compatible resource
manager. Information includes load and job distribution. Interactive as well
as static output is available.

%prep
%setup -q

%build
%{__python} setup.py build

%install
%{__python} setup.py install -O1 --skip-build --root=$RPM_BUILD_ROOT
desktop-file-install --dir=${RPM_BUILD_ROOT}%{_datadir}/applications \
	usr/share/applications/pbsclusterviz.desktop
desktop-file-validate ${RPM_BUILD_ROOT}%{_datadir}/applications/pbsclusterviz.desktop
mkdir -p ${RPM_BUILD_ROOT}%{_datadir}/icons/hicolor/256x256/apps/
install usr/share/icons/hicolor/256x256/apps/pbsclusterviz.png \
	${RPM_BUILD_ROOT}%{_datadir}/icons/hicolor/256x256/apps/

%files
%doc README.md BUGS CHANGES TODO AUTHORS COPYING
%{_bindir}/pbs_cluster_status
%{_bindir}/pbs_gen_nodes_file

# add pbsclusterviz base files
%dir %{python_sitelib}/pbsclusterviz
%{python_sitelib}/pbsclusterviz/*.py
%{python_sitelib}/pbsclusterviz/*.pyc
%ghost %{python_sitelib}/pbsclusterviz/*.pyo

# desktop files
%dir %{_datadir}/icons/hicolor/256x256/apps
%{_datadir}/applications/pbsclusterviz.desktop
%{_datadir}/icons/hicolor/256x256/apps/pbsclusterviz.png

# the egg-info file built from distutils needs to be put into
# %{python_sitelib} as per the Fedora packaging guidelines
%{python_sitelib}/pbsclusterviz-*.egg-info

# config files
%dir %{_sysconfdir}/pbsclusterviz.d
%config(noreplace) %{_sysconfdir}/pbsclusterviz.d/clusterviz.conf
%config(noreplace) %{_sysconfdir}/pbsclusterviz.d/nodes

%changelog
* Thu Nov 7 2013 Paul Cochrane <paul@liekut.de> 0.7a-4
- packaging python egg-info file as per Fedorag packaging guidelines
- corrected changelog order as noted by Orion Poplawski (Fedora)
- updated source and url info to new GitHub repository location
- removed release information from tarball version number

* Thu Aug 1 2013 Paul Cochrane <paultcochrane@users.sourceforge.net> 0.7a-3
- removed %%clean as recommended by Veaceslav Mindru (Fedora)

* Fri Nov 30 2012 Paul Cochrane <paultcochrane@users.sourceforge.net> 0.7a-1
- made corrections to spec file after comments from Volker Fröhlich (Fedora)
  - added COPYING and AUTHORS
  - updated GPL text
  - using Name and Version macros in Source0
  - corrected license value
  - removed version dependencies from BuildRequires
  - added Requires packages

* Fri Nov 9 2012 Paul Cochrane <paultcochrane@users.sourceforge.net> 0.7a-1
- New spec file for pbsclusterviz-0.7a
